use crate::error::SqliteTasksError;
use serde_derive::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct JobPublication {
  pub id: String,
  pub job_id: String,
  pub page_id: String,
  pub platform: String,
  pub target_config_id: Option<String>,
  pub browser_profile_id: String,
  pub status: String,
  pub scheduled_at: Option<i64>,
  pub approved_at: Option<i64>,
  pub started_at: Option<i64>,
  pub posted_at: Option<i64>,
  pub attempt_count: i64,
  pub idempotency_key: String,
  pub platform_post_id: Option<String>,
  pub post_url: Option<String>,
  pub title: Option<String>,
  pub caption: Option<String>,
  pub hashtags_json: Option<String>,
  pub description: Option<String>,
  pub video_path: Option<String>,
  pub last_error_code: Option<String>,
  pub last_error_message: Option<String>,
  pub created_at: i64,
  pub updated_at: i64,
}

#[derive(Debug, sqlx::FromRow)]
pub struct RawJobPublication {
  pub id: String,
  pub job_id: String,
  pub page_id: String,
  pub platform: String,
  pub target_config_id: Option<String>,
  pub browser_profile_id: String,
  pub status: String,
  pub scheduled_at: Option<i64>,
  pub approved_at: Option<i64>,
  pub started_at: Option<i64>,
  pub posted_at: Option<i64>,
  pub attempt_count: i64,
  pub idempotency_key: String,
  pub platform_post_id: Option<String>,
  pub post_url: Option<String>,
  pub title: Option<String>,
  pub caption: Option<String>,
  pub hashtags_json: Option<String>,
  pub description: Option<String>,
  pub video_path: Option<String>,
  pub last_error_code: Option<String>,
  pub last_error_message: Option<String>,
  pub created_at: i64,
  pub updated_at: i64,
}

pub(crate) fn raw_into_job_publication(raw: RawJobPublication) -> Result<JobPublication, SqliteTasksError> {
  Ok(JobPublication {
    id: raw.id,
    job_id: raw.job_id,
    page_id: raw.page_id,
    platform: raw.platform,
    target_config_id: raw.target_config_id,
    browser_profile_id: raw.browser_profile_id,
    status: raw.status,
    scheduled_at: raw.scheduled_at,
    approved_at: raw.approved_at,
    started_at: raw.started_at,
    posted_at: raw.posted_at,
    attempt_count: raw.attempt_count,
    idempotency_key: raw.idempotency_key,
    platform_post_id: raw.platform_post_id,
    post_url: raw.post_url,
    title: raw.title,
    caption: raw.caption,
    hashtags_json: raw.hashtags_json,
    description: raw.description,
    video_path: raw.video_path,
    last_error_code: raw.last_error_code,
    last_error_message: raw.last_error_message,
    created_at: raw.created_at,
    updated_at: raw.updated_at,
  })
}
