import type { SoundItem } from "../../types";

export const SOUNDS_LIBRARY: SoundItem[] = [
  {
    id: "sfx-adult-fem",
    name: "Adult-Fem_Exertion-Grunt_VKT_17547",
    category: "sound-effects",
    durationLabel: "00:01",
    durationSec: 1,
    thumb: "linear-gradient(135deg,#2d3139,#5a6270)",
  },
  {
    id: "music-adventure",
    name: "Adventure Cinematic",
    category: "music",
    durationLabel: "01:37",
    durationSec: 97,
    thumb: "linear-gradient(135deg,#363b45,#484f5c)",
  },
  {
    id: "music-aesthetic-1",
    name: "Aesthetic",
    category: "music",
    durationLabel: "00:44",
    durationSec: 44,
    thumb: "linear-gradient(135deg,#3a3f4a,#4a5160)",
  },
  {
    id: "music-aesthetic-2",
    name: "Aesthetic",
    category: "music",
    durationLabel: "01:09",
    durationSec: 69,
    thumb: "linear-gradient(135deg,#2d3139,#5a6270)",
  },
  {
    id: "music-african-drum",
    name: "African Drum Synthesizer Fashion Africana",
    category: "music",
    durationLabel: "02:28",
    durationSec: 148,
    thumb: "linear-gradient(135deg,#363b45,#484f5c)",
  },
  {
    id: "music-african-drums-sun",
    name: "African Drums In Love With The Sun",
    category: "music",
    durationLabel: "01:40",
    durationSec: 100,
    thumb: "linear-gradient(135deg,#3a3f4a,#4a5160)",
  },
  {
    id: "music-afro-groove",
    name: "Afro Groove Reverie",
    category: "music",
    durationLabel: "02:01",
    durationSec: 121,
    thumb: "linear-gradient(135deg,#2d3139,#5a6270)",
  },
  {
    id: "music-afrobeat-dancehall",
    name: "Afrobeat Dancehall Reggae(1283226)",
    category: "music",
    durationLabel: "01:43",
    durationSec: 103,
    thumb: "linear-gradient(135deg,#363b45,#484f5c)",
  },
  {
    id: "music-afrobeat-reggae",
    name: "Afrobeat reggae with a refreshing and fast-paced feel(1027325)",
    category: "music",
    durationLabel: "02:11",
    durationSec: 131,
    thumb: "linear-gradient(135deg,#3a3f4a,#4a5160)",
  },
  {
    id: "music-aggressive-techno",
    name: "Aggressive Slow Techno",
    category: "music",
    durationLabel: "02:37",
    durationSec: 157,
    thumb: "linear-gradient(135deg,#2d3139,#5a6270)",
  },
  {
    id: "sfx-airplane",
    name: "Airplane-WW2-Fighter-Plane-Ext_65vt9-0170",
    category: "sound-effects",
    durationLabel: "00:08",
    durationSec: 8,
    thumb: "linear-gradient(135deg,#363b45,#484f5c)",
  },
  {
    id: "sfx-whoosh",
    name: "Cinematic Whoosh",
    category: "sound-effects",
    durationLabel: "00:03",
    durationSec: 3,
    thumb: "linear-gradient(135deg,#3a3f4a,#4a5160)",
    favorite: true,
  },
];

export const SOUNDS_COUNTS = {
  music: 1078,
  "sound-effects": 656,
  "my-audio": 0,
} as const;
