[package]
name = "server_environment"
edition = "2018"
version = "0.0.1"
authors = [
    "Brandon Thomas <bt@brand.io>",
    "Brandon Thomas <echelon@gmail.com>",
]
publish = false

[lib]
# NB: Didn't even bother checking for "server_environment" crate. We wouldn't use it.
name = "server_environment"
path = "src/lib.rs"

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-build-acceleration"]

[dependencies]
# Internal
# (None yet)

# Workspace hack (faster compile times)
workspace-build-acceleration = { version = "0.1", path = "../../workspace-build-acceleration" }

# External
# (None yet)

[dev-dependencies]
# None yet
