[package]
name = "collections"
edition = "2018"
version = "0.0.1"
authors = [
    "Brandon Thomas <bt@brand.io>",
    "Brandon Thomas <echelon@gmail.com>",
]
publish = false

[lib]
# NB: Public "collections" crate is not yet taken (!!), so we're fine to use this internally for now.
name = "collections"
path = "src/lib.rs"

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-build-acceleration"]

[dependencies]
# Internal
#errors = { path = "../../errors" }

# Workspace hack (faster compile times)
workspace-build-acceleration = { version = "0.1", path = "../../../workspace-build-acceleration" }

# External
# KEEP THIS TO A MINIMUM OR NIL.
rand = "0.8.5"

[dev-dependencies]
# None yet
