"""
Mate engine facade — single entry for router / services (Phase 1).

Public HTTP contracts stay on FastAPI router.
This module re-exports ``src.service`` so callers use ``engines.mate.facade``
instead of importing service ad-hoc. No business logic copy.
"""

from __future__ import annotations

# Re-export entire Mate service surface (router-compatible names).
from src.service import (  # noqa: F401
    create_draft,
    save_draft,
    save_draft_async,
    get_draft,
    add_videos,
    add_videos_async,
    add_audios,
    add_audios_async,
    add_images,
    add_images_async,
    add_sticker,
    add_sticker_async,
    add_keyframes,
    add_keyframes_async,
    add_captions,
    add_captions_async,
    add_effects,
    add_effects_async,
    add_filters,
    add_filters_async,
    add_masks,
    add_masks_async,
    add_text_style,
    get_text_animations,
    get_image_animations,
    get_filters,
    get_effects,
    easy_create_material,
    easy_create_material_async,
    gen_video,
    gen_video_status,
    get_gen_video_active_count,
    get_audio_duration,
    timelines,
    audio_timelines,
    audio_infos,
    imgs_infos,
    caption_infos,
    effect_infos,
    filter_infos,
    keyframes_infos,
    video_infos,
    search_sticker,
    get_url,
    str_list_to_objs,
    str_to_list,
    objs_to_str_list,
    DraftPublishError,
    publish_draft,
)

__all__ = [
    "create_draft",
    "save_draft",
    "save_draft_async",
    "get_draft",
    "add_videos",
    "add_videos_async",
    "add_audios",
    "add_audios_async",
    "add_images",
    "add_images_async",
    "add_sticker",
    "add_sticker_async",
    "add_keyframes",
    "add_keyframes_async",
    "add_captions",
    "add_captions_async",
    "add_effects",
    "add_effects_async",
    "add_filters",
    "add_filters_async",
    "add_masks",
    "add_masks_async",
    "add_text_style",
    "get_text_animations",
    "get_image_animations",
    "get_filters",
    "get_effects",
    "easy_create_material",
    "easy_create_material_async",
    "gen_video",
    "gen_video_status",
    "get_gen_video_active_count",
    "get_audio_duration",
    "timelines",
    "audio_timelines",
    "audio_infos",
    "imgs_infos",
    "caption_infos",
    "effect_infos",
    "filter_infos",
    "keyframes_infos",
    "video_infos",
    "search_sticker",
    "get_url",
    "str_list_to_objs",
    "str_to_list",
    "objs_to_str_list",
    "DraftPublishError",
    "publish_draft",
]
